training:
  output_dir: runs/
  batch_size: 32
  num_workers: 0
  trainer_args:
    max_epochs: 3
    accelerator: gpu
    devices: 1
    accumulate_grad_batches: 1
    limit_val_batches: 0.05

  evaluation:
    mols_to_sample: 64 # how many molecules to sample during evaluation
    sample_interval: 0.25 # how often to sample molecules during training, measured in epochs
    val_loss_interval: 0.5 # how often to compute validation set loss during training, measured in epochs

wandb:
  project: mol-fm
  group: "dev"
  name: "dev run"
  mode: online # can be disabled, online, offline

lr_scheduler:
  # to turn off warmup and restarts, set both warmup_length and restart_interval to 0
  base_lr: 1.0e-4
  warmup_length: 0
  restart_interval: 0 # 0 means no restart
  restart_type: 'linear'

# dataset:
#   raw_data_dir: data/raw/
#   processed_data_dir: data/geom_dev
#   # in order to disbale explicit hydrogens, just remove 'H' from atom_map
#   atom_map: ['C', 'H', 'N', 'O', 'F', 'P', 'S', 'Cl', 'Br', 'I'] # TODO: check the list of atoms contained in geomdrugs
#   dataset_name: geom # only geom is supported for now
#   dataset_size: 500

dataset:
  raw_data_dir: data/qm9_raw
  processed_data_dir: data/qm9
  # in order to disbale explicit hydrogens, just remove 'H' from atom_map
  atom_map: ['C', 'H', 'N', 'O', 'F',] 
  dataset_name: qm9 # must be qm9 or geom
  dataset_size: 

checkpointing:
  save_last: True
  # monitor: 'val_total_loss'
  # every_n_epochs: 1

mol_fm:
  parameterization: vector-field # can be "endpoint" or "vector-field"  
  time_scaled_loss: True
  exclude_charges: False
  total_loss_weights:
    x: 1.0
    a: 1.0
    c: 1.0
    e: 1.0
  prior_config:
    x:
      align: True
      type: 'centered-normal'
      kwargs: {std: 1.0}
    a:
      align: False
      type: 'gaussian'
      kwargs: {}
    c:
      align: False
      type: 'c-given-a'
      kwargs: {blur: 0.15}
    e:
      align: False
      type: 'marginal'
      kwargs: {blur: 0.15}

vector_field:
  n_vec_channels: 16
  n_hidden_scalars: 64
  n_hidden_edge_feats: 64
  n_recycles: 1
  n_molecule_updates: 3
  separate_mol_updaters: True
  convs_per_update: 1
  n_cp_feats: 4
  n_message_gvps: 3
  n_update_gvps: 3
  message_norm: 100
  rbf_dmax: 12
  rbf_dim: 16

interpolant_scheduler:
  schedule_type: # can be 'cosine', 'linear' or a dictionary with keys 'x', 'a', 'c', 'e'
    x: 'cosine'
    a: 'linear'
    c: 'linear'
    e: 'linear'
  
  cosine_params:
    x: 1
    a: 2.0
    c: 2.0
    e: 1.5

