training:
  batch_size: 8
  num_workers: 0
  trainer_args:
    max_epochs: 1
    accelerator: gpu
    devices: 1
    accumulate_grad_batches: 1

wandb:
  project: mol-fm
  group: "dev"
  name:
  mode: offline # can be disabled, online, offline
  save_dir: runs

lr_scheduler:
  base_lr: 1.0e-4
  warmup_length: 1
  restart_interval: 0 # 0 means no restart
  restart_type: 'linear'

dataset:
  raw_data_dir: data/raw/
  processed_data_dir: data/geom_dev
  atom_map: ['C', 'H', 'N', 'O', 'F', 'P', 'S', 'Cl', 'Br', 'I'] # TODO: check the list of atoms contained in geomdrugs
  dataset_name: geom # only geom is supported for now
  n_conformers: 4
  dataset_size: 500

checkpointing:
  save_last: True
  every_n_train_steps: 5

mol_fm:
  time_scaled_loss: True
  total_loss_weights:
    x: 1.0
    a: 1.0
    c: 1.0
    e: 1.0

vector_field:
  n_vec_channels: 16
  n_hidden_scalars: 64
  n_hidden_edge_feats: 64
  n_recycles: 1
  n_molecule_updates: 1
  convs_per_update: 2
  n_message_gvps: 3
  n_update_gvps: 3
  message_norm: 100
  rbf_dmax: 20
  rbf_dim: 16

interpolant_scheduler:
  schedule_type: 'cosine'
  cosine_params:
    x: 1
    a: 2
    c: 2
    e: 1.5

