training:
  output_dir: runs/runs_fm3/
  batch_size: 12
  num_workers: 6
  ema_decay: 0
  max_num_edges: 50000
  trainer_args:
    max_epochs: 20
    accelerator: gpu
    devices: 4
    num_nodes: 1
    strategy: ddp_find_unused_parameters_true
    accumulate_grad_batches: 1
    limit_val_batches: 0.002

  evaluation:
    mols_to_sample: 100 # how many molecules to sample during evaluation
    sample_interval: 0.05 # how often to sample molecules during training, measured in epochs
    val_loss_interval: 0.05 # how often to compute validation set loss during training, measured in epochs

wandb:
  project: mol-fm
  entity: iandunn
  group:
  name: fm3_repeat
  mode: online # can be disabled, online, offline

lr_scheduler:
  # to turn off warmup and restarts, set both warmup_length and restart_interval to 0
  base_lr: 1.0e-4
  warmup_length: 0.0
  restart_interval: 0 # 0 means no restart
  restart_type: 'linear'
  weight_decay: 1.0e-12

dataset:
  raw_data_dir: data/geom_raw/
  processed_data_dir: data/geom_full_kekulized/
  # atom_map: ['C', 'H', 'N', 'O', 'F', 'P', 'S', 'Cl', 'Br', 'I', 'As', 'Hg', 'Bi', 'Se']
  atom_map: ['C', 'H', 'N', 'O', 'F', 'P', 'S', 'Cl', 'Br', 'I',] # I removed As, Hg, Bi, Se. As, Hg, and Se are not in the dataset, and Bi is virtually not in the dataset.. p(a = Bi) = 1.0e-8
  dataset_name: geom # only geom is supported for now
  dataset_size:
  confs_per_mol: 

checkpointing:
  save_last: True
  save_top_k: 6
  monitor: 'val_total_loss'
  every_n_epochs: 1

mol_fm:
  explicit_aromaticity: false
  distort_p: 0.2
  fake_atom_p: 0.3
  parameterization: ctmc # can be "endpoint", "vector-field", or "dirichlet"
  time_scaled_loss: True
  total_loss_weights:
    x: 3.0
    a: 0.4
    c: 1.0
    e: 2.0
  prior_config:
    x:
      align: True
      type: 'centered-normal'
      kwargs: {std: 1.0}
    a:
      align: False
      type: 'ctmc'
      kwargs: {}
    c:
      align: False
      type: 'ctmc'
      kwargs: {}
    e:
      align: False
      type: 'ctmc'
      kwargs: {}

vector_field:
  self_conditioning: True
  stochasticity: 30.0
  high_confidence_threshold: 0.9
  n_vec_channels: 32
  update_edge_w_distance: True
  n_hidden_scalars: 256
  n_hidden_edge_feats: 128
  s_message_dim: 
  v_message_dim: 
  n_expansion_gvps: 3
  attention: False
  n_heads: 32
  n_recycles: 1
  separate_mol_updaters: True
  n_molecule_updates: 6
  convs_per_update: 1
  n_cp_feats: 4
  n_message_gvps: 3
  n_update_gvps: 3
  message_norm: sum
  rbf_dmax: 10
  rbf_dim: 32
  time_embedding_dim: 64
  a_token_dim: 64
  c_token_dim: 64
  e_token_dim: 64

interpolant_scheduler:
  schedule_type:
    x: 'linear'
    a: 'linear'
    c: 'linear'
    e: 'linear'
  # cosine_params:
  #   x: 1
  #   a: 2
  #   c: 2
  #   e: 2

